theme: jekyll-theme-minimal
title: Sajeth Jonathan
description: ğŸ‘¨â€ğŸ’» Cybersecurity Student
logo : /assets/img/logo.jpg
author: Sajeth Jonathan
location: ğŸ“  Colombo, Srilanka
email: sws.jona@outlook.com
linkedin: https://www.linkedin.com/in/sajethjonathan/
twitter: https://twitter.com/swsjona
medium: https://medium.com/@sws.jona

plugins:
  - jekyll-seo-tag